### ISSUE TITLE
SteamLogin 권한 확인

### ISSUE THREAD

**Issue by leebuwon** [TeamSteam-11/TeamSteam#10]
- [x] 스팀 로그인 권한 확인
- [x] p6spy 추가

---
url을 통한 스팀 로그인 확인

---

openId 참조 사이트 ( url 참조 )
https://wiki.brianturchyn.net/programming/apis/steam/

p6spy는 sqlformatter로 
```
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
```

대체해주신다고 보면됩니다.
